server:
  port: 8090

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/wmszzk?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wmszzk?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    type-aliases-package: com.wms.entity
logging:
  level:
    com.baomidou.mybatisplus: DEBUG
    org.apache.ibatis: DEBUG
